### PR TITLE
Total engine refactoring

### LINKED ISSUE #6: Remember the last used input mode
**After #7, #11, #14.**

Sometimes, in specific apps, one needs to type using a non-default mode, for example, always use Abc, instead of predictive, or always use capitals. However, every time a text field is focused, it starts with the default mode. Switching to the desired mode all the time is very annoying, so let's fix it.

- Remember the language
- Remember the text case
- Remember the mode (predictive, text, numeric)
- Remove the "default mode" setting from the UI and just use the last mode. Perhaps, it could be changed dynamically in the background, when the user changes the input mode, to avoid big code refactoring.

### LINKED ISSUE #12: Redefine "0" key behaviour
- ~~Get rid of the "Space on 0" option. Only "0" can type space.~~ - Done
- ~~In predictive mode:~~
  - ~~Short press: Types a space; ends word composition~~
  - ~~Long press: Types "0"~~
- ~~In text mode:~~
  - ~~Short press: Choose between "0", "+", " ", "\n". (current behaviour + "\n")~~
  - ~~Long press: Types "0"~~
- ~~In numeric mode:~~
  - ~~Short press: Types "0"~~
  - ~~Long press: Types "+"~~
- ~~Update the user manual.~~

### LINKED ISSUE #13: Redefine "1" key behaviour
- ~~Predictive and text modes~~
  - ~~Short press:~~
    - ~~Types a special character (one of: `.,-?!'@:/;1`).~~
    - ~~Breaks word composition.~~
    - ~~Consider the discussion in [Clam-#12](https://github.com/Clam-/TraditionalT9/issues/12).~~
    - ~~Also, check with the Google keyboard if any other frequently useful character should be added.~~
  - ~~Double press (Predictive mode only): Types one of: `:)` `:D` `;)` `:(` `:*` `:P`. Consider adding other smileys.~~
  - ~~Long press: Open special character screen.~~ Not possible at the moment. It will be done in #27.
- ~~Numeric mode:~~
  - ~~Short press: Types "1"~~
- ~~Update the user manual.~~

### LINKED ISSUE #14: Redefine the Special function keys
After #24 and #25. They are required for implementing the "next language" function.

- ~~(mode key) (disabled in numeric fields)~~
	- ~~Short press: Cycles between: abc/ABC/Predictive/123~~
	- ~~Short press while composing a word: Changes the case of the current word~~
	- ~~Long press: Selects the next language~~
- ~~(backspace key)~~ 
	- ~~Short press: Backspace~~
	- ~~Long press: Continuous delete~~. When "BACK" is selected, long pressing is not possible.
- ~~(other actions key)~~
	- ~~Short press: Add a word to the user dictionary~~
	- ~~Long press: open the preferences screen.~~
- ~~In numeric fields, "#" and "*" can not have special functions. They can only type the respective characters. Also, changing the mode is not possible.~~ Done
- ~~Update the user manual.~~
- ~~Make sure `TraditionalT9.updateStatusIcon()` only updates the icon.~~ Done

### LINKED ISSUE #15: Redefine the soft keys
**After #19.**
- ~~Right, short:~~
  - ~~Backspace. Here is a [sort of an example](https://github.com/Clam-/TraditionalT9/commit/e24f23e768a612971dfc9c91f89a6b6fbffd6d01).~~
  - ~~It has this icon: ⌫~~
- ~~Left, short~~
  - ~~Open settings.~~
  - ~~It has this icon: ⚙~~
- ~~Remove center~~ _Let's keep it for now_
- ~~They keys are much smaller, they don't need to take up 1/3 of the screen width.~~
- ~~Update the user manual.~~

### LINKED ISSUE #18: TraditionalT9.java cleanup
After #7.

The file is: `TraditionalT9.java`
- ~~The keyUp/keyDown handlers contain way too many `if .. else` clauses. Refactor them to be `switch .. case` for better readability.~~
- ~~in addition the keyDown handler does too many things. Try minimizing the logic there, to avoid weird user experience when holding a key, but it is picked up by keyDown instead.~~
- ~~There may be too many action handlers that may be causing inadequate input behavior (missed or doubled key presses). Try reducing them.~~
- ~~Do not allow global key remapping. Remove that option.~~ 
- ~~Do not validate the key mode in `updateStatusIcon()`. Do so when actually changing it or on the first run.~~
- ~~Clean up `onStartInput()`~~

### LINKED ISSUE #24: Do not mix characters from different languages
- Remove the non-English words from the English dictionary.
- In CharMap.java, each language contains only its own characters.

### LINKED ISSUE #25: Create separate language classes
After #24.

Currently, different bits of a single language are spread across `LangHelper.java` and `CharMap.java`. This means each file has multiple responsibilities and also will make adding of new languages more and more difficult.
- ~~Create base latin/cyrillic language classes~~ - this is not a good idea, because it provides no flexibility for adding special letters in the middle of the candidates for a key.
- ~~Derive all languages from the base classes. Each language is represented as much as possible by a single class. It contains all its characters, icons, capital letter rules, etc.~~
- ~~Redo language changing using "#".~~
- ~~Try getting rid of the double index system. ID means index and there must be only one.~~ Almost done. The UI will be cleaned up in #29 
- ~~Ensure inserting the words from the assets still works.~~
- ~~Еnsure selecting a language from the Preferences screen still works.~~
- ~~Do not translate the language names.~~ - in #29 
- ~~Do not use `CharMap.java` and `LangHelper.java` anymore. Delete them.~~ `LangHelper.java` is still used in the legacy preferences code. Removing it would be possible after #29.
- ~~Delete all unused icons.~~
- ~~Reintroduce all languages.~~
- ~~Update the README about adding new languages.~~

### LINKED ISSUE #26: Cleanup the database package
- ~~Remove all own dictionary related settings, functions and strings/translations, such as "nuke", "backup".~~ done in #7
- `DatabaseHelper`: 
  - It is a database-pure interface. It has no knowledge about TT9.
  - It contains insert, delete, truncate and other core functions, some of which are currently in `T9DB`
- `T9DB`
  - contains application-specific logic, such as incrementing word priority and getting words for a given digit sequence
  - Optimize the `updateWords()` function. Get rid of text case conversions. Simplify the code even more, if possible. Give it a more meaningful name.

### LINKED ISSUE #40: Remove the "AbsSym" dialogs and all related resources
These no longer function properly. They will be remade in #27.
Don't forget to remove the colors from `colors.xml`.

### LINKED ISSUE #41: Make dictionary clearing asynchronous
Truncating the dictionary database takes a couple of seconds and the UI remains blocked, which is undesirable.

- Run the database query asynchronously.
- ~~Display some sort of a progress bar, possibly the one from #17 .~~ - there is no progress to display, it is just a single DB query. Also, it happens so fast, there is no need of a progress bar.
- Display a notification or a toast when it is done. Experiment and decide which one is better.

### LINKED ISSUE #43: New language choice is not always applied until TT9 is restarted
- Go to an input field to activate TT9
- Open the preferences and select English.
- Go back to type something.
- Go to the preferences again, deselect English and select another language

English remains active, even though it is not in the list of enabled languages.

Expected:
- The last used language is selected, if it is in the list of enabled ones.
- Otherwise, the first language in the enabled list is selected.
- If the list is empty, reset the settings and use language 1.

This is a regression due to #18.

### LINKED ISSUE #45: Holding a key to type a number must end composition
... otherwise it is very confusing.

This is a regression due to #18.

### LINKED ISSUE #46: Backspace causes side effects in the number dialing field
- Go to the Android home screen
- Start typing a phone number
- Erase a digit
- Type again

The erased digit pops up again, but they must not.

This is a regression, caused by #18

### LINKED ISSUE #47: The currently selected candidate is not previewed in the input field
A regression after #18

### LINKED ISSUE #49: Take care of the translations and strings
- At the end of the big cleanup there may some unused resources in `res` folder. 
- Make sure to check for unused buttons 
- Remove any unused translations.
- Translate missing strings, whenever possible.

After #50

### LINKED ISSUE #50: Display a toast when user requests adding a new word, but it is not possible
Word adding is possible only in Predictive mode. If the user clicks the "Add Word" button in any other mode, nothing happens, which is confusing. To make it clear why is that, display a toast, saying: "You can add words in Predictive mode only".

Until #55  is done, adding words should remain completely disabled.

### LINKED ISSUE #52: Sort out showing the window in onOK()
Research whether showing the window there is necessary at all. `showWindow()` happening there was inherited from the original version, but it looks redundant. 

Manage the window visibility and set any required flags in `onRestart()`.

### LINKED ISSUE #56: Single characters are inserted multiple times in the database
Single letters and punctuation for each language are inserted multiple times in the database, but they shouldn't be. This is a regression caused by #26.

- Verify there is no missing unique index
- Insert only lowercase characters.

This is a regression caused by #18.

### LINKED ISSUE #57: Throw an error when there are languages with duplicate IDs
Make languages future-proof. In `LanguageCollection` throw an error when there are languages with duplicate IDs.

### LINKED ISSUE #59: Crash when switching IMEs
1. Choose Predictive mode
2. Select another IME as the default one
3. Close any open applications
4. Open an application where you can type
5. Go to a text field to make the other IME appear
6. Switch to TT9
7. Try typing something

This causes an unknown error and a crash. When Android resurrects TT9, try typing again and it will crash again.

This is a regression caused by #18.

### LINKED ISSUE #61: Clean up all logs from the production release
Make sure there are no `Log.d()` or whatnot when building a Release `.apk`. Just create a simple wrapper class with a single "debug" setting.

### LINKED ISSUE #62: Do not suggest numbers as "words" in Predictive mode
Double check with the Nokia 3310, though.

### LINKED ISSUE #63: Ensure invalid input and error handling to perevent bugs
After the big refactoring, handle invalid input and errors in:

- DictionaryDb
- Language.getUpperCaseChars()
- CandidateView.setSuggestions()
- T9Preferences (or stay with PreferenceValidator?)

### LINKED ISSUE #64: Accepting "простотия" causes a crash
Fix it!

### LINKED ISSUE #65: Remove all references to TraditionalT9 from KeypadHandler
The `KeypadHandler` is supposed to be a generic handler. It must not know about the special T9 logic.

- Add a `trackNumPress` and `trackNumLongPress` flag (or function) in TraditionalT9, in the places where MODE_123 is checked.
- The input mode and text case functions are OK to go in `TraditionalT9`.

### LINKED ISSUE #67: Using space to accept a single letter in Predictive mode, does not cause the letter priority to be updated

### LINKED ISSUE #70: Backspace must be pressed twice to delete the first letter of a word in Predictive mode
Deleting a letter must require only one key press.

This is a regression due to #18

### LINKED ISSUE #71: Typing "бояяяяя" in Predictive mode causes unexpected random suggestions
Also, trying to erase the word seems to work, but it is not reflected in the UI.

Investigate and fix!

### PR DESCRIPTION
**Pull request by sspanak**
Closes #15 
Closes #18 
Closes #24 
Fixes #43 
Fixes #45 
Fixes #47
Closes #6 
Closes #40 
Closes #25 
Closes #12 
Closes #13 
Closes #14 
Closes #41 
Closes #26 
Fixes #56 
Fixes #59 
Closes #52 
Fixes #46 
Closes #50 
Closes #57 
Closes #61 
Fixes #64 
Fixes #63 
Fixes #67 
Fixes #71 
Fixes #70 
Closes #49 
Fixes #65 
Closes #62

### CODE REVIEW

File: src/io/github/sspanak/tt9/languages/definitions/Bulgarian.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+		icon = R.drawable.ime_lang_bg;
+		abcLowerCaseIcon = R.drawable.ime_lang_cyrillic_lower;
+		abcUpperCaseIcon = R.drawable.ime_lang_cyrillic_upper;
+
+		characterMap = new ArrayList<>(Arrays.asList(
+			Punctuation.Secondary, // 0
+			Punctuation.Main, // 1
+			new ArrayList<>(Arrays.asList("а", "б", "в", "г")), // 2
+			new ArrayList<>(Arrays.asList("д", "е", "ж", "з")), // 3
+			new ArrayList<>(Arrays.asList("и", "й", "к", "л")), // 4
```
Comment (sspanak) [inline src/io/github/sspanak/tt9/languages/definitions/Bulgarian.java]:
```suggestion
			new ArrayList<>(Arrays.asList("и", "й", "к", "л", "ѝ")), // 4
```
