### PR TITLE
Zero improvements

### LINKED ISSUE #78: Add a "space after punctuation or words" setting
- ~~Add an on/off option for automatically adding a space after `)`, `]`, `,`, `.`, `?`, `:`, `;` or `!`, or after accepting a suggestion (on OK).~~
- ~~Name: "Automatic space".~~
- ~~Summary: "Automatically add a space after punctuation or words".~~
- ~~Disable it in specialized text fields.~~
- ~~Trim 1 space before the punctuation listed above. Do so only once.~~
- ~~After deleting one space before punctuation, make sure to restore it before emoji.~~
- ~~Attempt using the `digitSequence` instead of the current word for determining what to do.~~

Predictive Mode only.

After #29

### LINKED ISSUE #125: Selecting an emoji sometimes results in broken characters
This was probably a problem since the beginning, but #122 revealed it.

- Go to a text field where you can type
- Press 1-key to display punctuation
- Select "?"
- Press 1-key again, to go to emoji

Result:
Since now the first emoji in the list is ":slightly_smiling_face:", somehow, when combined with "?", it results in invalid characters in the text field. Selecting another emoji and going back to the first one, fixes the broken character(s).

Expected Result:
The emoji is displayed properly.

### PR DESCRIPTION
**Pull request by sspanak**
Closes https://github.com/sspanak/tt9/issues/113
Closes https://github.com/sspanak/tt9/issues/102
Closes #78 
Fixes #125 
Additionally, made the automatic capitalization a setting.

### CODE REVIEW

**Comment by sspanak** [comment]
Must fix #125, before merging this.

File: src/io/github/sspanak/tt9/ime/modes/ModePredictive.java [hunk 1]
```diff
@@ -86,18 +95,102 @@ public boolean onNumber(Language l, int key, boolean hold, boolean repeat) {
...
+	 * words.
+	 */
+	private boolean shouldAddAutoSpaceAfterWord(EditorInfo inputField, boolean isWordAcceptedManually, int incomingKey) {
+		return
+			// 0 and 1 do not type letters. They are handled in "shouldAddAutoSpaceAfterPunctuation()".
+			incomingKey != 0 && incomingKey != 1
+			// Do not add space when auto-accepting words, because it feels very confusing when typing.
+			&& isWordAcceptedManually
+			// Emoji
+			&& !lastAcceptedSequence.startsWith("11")
```
Comment (sspanak) [inline src/io/github/sspanak/tt9/ime/modes/ModePredictive.java]:
```suggestion
			&& !lastAcceptedSequence.startsWith("1")
```

Otherwise, it allows a space after any punctuation.

File: src/io/github/sspanak/tt9/ime/modes/ModePredictive.java [hunk 2]
```diff
@@ -163,11 +259,35 @@ public boolean setWordStem(Language language, String wordStem, boolean exact) {
...
+	 */
+	private boolean loadStaticSuggestions() {
+		if (digitSequence.equals("0")) {
+			suggestions = Punctuation.Secondary;
+		} else if (containsOnly1.matcher(digitSequence).matches()) {
+			if (digitSequence.length() == 1) {
+				suggestions = Punctuation.Main;
+			} else {
+				digitSequence = digitSequence.length() <= maxEmojiSequence.length() ? digitSequence : maxEmojiSequence;
+				suggestions = Punctuation.getEmoji(digitSequence.length() - 2);
```
Comment (sspanak) [inline src/io/github/sspanak/tt9/ime/modes/ModePredictive.java:287]: Double check this. It may be causing #125. If not just set the composing text properly and fix the bug.

File: src/io/github/sspanak/tt9/ime/modes/InputMode.java [hunk 3]
```diff
@@ -69,6 +70,13 @@ public ArrayList<String> getSuggestions(Language language) {
 	// Utility
 	abstract public int getId();
 	abstract public int getSequenceLength(); // The number of key presses for the current word.
+
+	public boolean shouldAddAutoSpace(EditorInfo inputField, boolean isWordAcceptedManually, int incomingKey) {
+		return false;
+	}
+	public boolean shouldDeletePrecedingSpace(EditorInfo inputField) { return false; }
```
Comment (sspanak) [inline src/io/github/sspanak/tt9/ime/modes/InputMode.java]: Let's keep consistent code style...

File: src/io/github/sspanak/tt9/ime/modes/ModePredictive.java (hunk 1 above)
Comment (sspanak) [reply src/io/github/sspanak/tt9/ime/modes/ModePredictive.java]: Done.

File: src/io/github/sspanak/tt9/ime/modes/InputMode.java (hunk 3 above)
Comment (sspanak) [reply src/io/github/sspanak/tt9/ime/modes/InputMode.java]: Done.

File: src/io/github/sspanak/tt9/ime/modes/ModePredictive.java (hunk 2 above)
Comment (sspanak) [reply src/io/github/sspanak/tt9/ime/modes/ModePredictive.java:287]: Fixed.

File: src/io/github/sspanak/tt9/ime/modes/ModePredictive.java [hunk 4]
```diff
@@ -86,18 +95,104 @@ public boolean onNumber(Language l, int key, boolean hold, boolean repeat) {
...
+
+	/**
+	 * shouldAddAutoSpaceAfterPunctuation
+	 * Determines whether to automatically adding a space after certain punctuation signs makes sense.
+	 * The rules are similar to the ones in the standard Android keyboard (with some exceptions,
+	 * because we are not using a QWERTY keyboard here).
+	 */
+	private boolean shouldAddAutoSpaceAfterPunctuation(EditorInfo inputField, int incomingKey) {
+		return
+			incomingKey != 0
```
Comment (sspanak) [inline src/io/github/sspanak/tt9/ime/modes/ModePredictive.java:159]:
```suggestion
			incomingKey != 0
			&& !hold
```

Holding a key means typing numbers. The usual case is trying to type decimal number, but it could be something else. Either way, if we are typing number, we don't want to follow any grammar rules, so let's not modify the space.

File: src/io/github/sspanak/tt9/ime/modes/ModePredictive.java [hunk 5]
```diff
@@ -86,18 +95,104 @@ public boolean onNumber(Language l, int key, boolean hold, boolean repeat) {
...
+
+
+	/**
+	 * shouldAddAutoSpaceAfterPunctuation
+	 * Similar to "shouldAddAutoSpaceAfterPunctuation()", but determines whether to add a space after
+	 * words.
+	 */
+	private boolean shouldAddAutoSpaceAfterWord(EditorInfo inputField, boolean isWordAcceptedManually) {
+		return
+			settings.getAutoSpace()
```
Comment (sspanak) [inline src/io/github/sspanak/tt9/ime/modes/ModePredictive.java]: Same as above, consider not doing anything when a number key is being held.

File: src/io/github/sspanak/tt9/ime/modes/ModePredictive.java (hunk 4 above)
Comment (sspanak) [reply src/io/github/sspanak/tt9/ime/modes/ModePredictive.java:159]: Done.

File: src/io/github/sspanak/tt9/ime/modes/ModePredictive.java (hunk 5 above)
Comment (sspanak) [reply src/io/github/sspanak/tt9/ime/modes/ModePredictive.java]: Done.
